function [Ne, dNe]=buildnlin_der(xi,eta,zeta,elementtype)
if (strcmpi(elementtype,'hex'))
    dNe=1/8*[-(1-eta).*(1-zeta),(1-eta).*(1-zeta),(1+eta).*(1-zeta),...
        -(1+eta).*(1-zeta),-(1-eta).*(1+zeta),(1-eta).*(1+zeta),...
        (1+eta).*(1+zeta),-(1+eta).*(1+zeta);-(1-xi).*(1-zeta),-(1+xi).*(1-zeta),(1+xi).*(1-zeta),...
        (1-xi).*(1-zeta),-(1-xi).*(1+zeta),-(1+xi).*(1+zeta),...
        (1+xi).*(1+zeta),(1-xi).*(1+zeta);-(1-xi).*(1-eta),-(1+xi).*(1-eta),-(1+xi).*(1+eta),...
        -(1-xi).*(1+eta),(1-xi).*(1-eta),(1+xi).*(1-eta),...
        (1+xi).*(1+eta),(1-xi).*(1+eta)];
    Ne=1/8*[(1-xi).*(1-eta).*(1-zeta),(1+xi).*(1-eta).*(1-zeta),(1+xi).*(1+eta).*(1-zeta),...
        (1-xi).*(1+eta).*(1-zeta),(1-xi).*(1-eta).*(1+zeta),(1+xi).*(1-eta).*(1+zeta),...
        (1+xi).*(1+eta).*(1+zeta),(1-xi).*(1+eta).*(1+zeta)];
elseif (strcmpi(elementtype,'tet'))
    Ne=[xi, eta, zeta, 1-xi-eta-zeta];
    dNe=[1 0 0 -1;0 1 0 -1; 0 0 1 -1];
else
    error('unsuported element type');
end
end