function [h]=SampleEdgeTraction(x,y,z,e,k) % I think this is correct
global Params  NBC;
P = Params.P;
L = Params.L;
c = Params.c;
t = Params.t;
E = Params.E;
% switch NBC(e,k)
%     case 1
%         h = [ - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)];
%     case 3
%         h = [ - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)];
%         
%     case 5
%         h = [ - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)];
%         
% end
if mod(NBC(e,k),2)==1
    h =[ - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c), - (E*((pi*sin((pi*x)/(2*L))*cos((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*L) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*((pi*cos((pi*x)/(2*L))*sin((pi*y)/(2*c))*cos((pi*z)/(2*t)))/(2*c) + (pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)))/2 - (E*pi*cos((pi*x)/(2*L))*cos((pi*y)/(2*c))*sin((pi*z)/(2*t)))/(2*t)]';
end
end